# Generated by Django 4.2.3 on 2023-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='affiche',
            field=models.TextField(default="tu dois ecrire ce qui va etre afficher comme descrition premier du produit sur la page d' d'accueil"),
        ),
        migrations.AddField(
            model_name='habits',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habits',
            name='description',
            field=models.TextField(default="je suis Agerish Programmeur , j'aimerais que tu puisse remplir ce champs avec la description du produit"),
        ),
    ]
