# Generated by Django 4.2.3 on 2023-07-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_habits_affiche_habits_image_alter_habits_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.IntegerField(default=0)),
                ('Adresse', models.CharField(max_length=150)),
                ('Pays', models.CharField(max_length=150)),
                ('Ville', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Produit', models.CharField(max_length=150)),
                ('quantite', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-Date'],
            },
        ),
    ]
