# Generated by Django 4.2.3 on 2023-07-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0004_accesoire_de_mode_accessoire_de_meuble_basket_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Robe_boheme',
            new_name='Robeboheme',
        ),
    ]
