# Generated by Django 4.2.3 on 2023-07-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_rename_robe_boheme_robeboheme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Robeboheme',
            new_name='Robebohemes',
        ),
        migrations.AlterModelOptions(
            name='robebohemes',
            options={'ordering': ['-Date'], 'verbose_name': 'Robeboheme', 'verbose_name_plural': 'Robeboheme'},
        ),
    ]
