# Generated by Django 4.2.3 on 2023-07-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_rename_robeboheme_robebohemes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket_homme',
            new_name='Accesoiredemodes',
        ),
        migrations.RenameModel(
            old_name='Sandals_femme',
            new_name='Accessoiredemeubles',
        ),
        migrations.RenameModel(
            old_name='Bijoux_femme',
            new_name='Basketfemmes',
        ),
        migrations.RenameModel(
            old_name='Sandals_homme',
            new_name='Baskethommes',
        ),
        migrations.RenameModel(
            old_name='Les_hauts_homme',
            new_name='Baskets',
        ),
        migrations.RenameModel(
            old_name='T_shirt',
            new_name='Bijouxfemmes',
        ),
        migrations.RenameModel(
            old_name='Machine_electronique',
            new_name='Bijouxhommes',
        ),
        migrations.RenameModel(
            old_name='Accesoire_de_mode',
            new_name='Bijouxs',
        ),
        migrations.RenameModel(
            old_name='Robe_courte',
            new_name='Jupecourtes',
        ),
        migrations.RenameModel(
            old_name='Basket',
            new_name='Jupelongues',
        ),
        migrations.RenameModel(
            old_name='Robe_soiree',
            new_name='Leshautsfemmes',
        ),
        migrations.RenameModel(
            old_name='Les_hauts_femme',
            new_name='Leshautshommes',
        ),
        migrations.RenameModel(
            old_name='T_shirt_homme',
            new_name='Machineelectroniques',
        ),
        migrations.RenameModel(
            old_name='Robe_longue',
            new_name='Periquebresiliennes',
        ),
        migrations.RenameModel(
            old_name='Perique_naturel',
            new_name='Periquehumainhairs',
        ),
        migrations.RenameModel(
            old_name='Perique_humain_hair',
            new_name='Periquenaturels',
        ),
        migrations.RenameModel(
            old_name='Perique_sinthetique',
            new_name='Periqueperruviennes',
        ),
        migrations.RenameModel(
            old_name='Perique_bresilienne',
            new_name='Periquesinthetiques',
        ),
        migrations.RenameModel(
            old_name='Bijoux_homme',
            new_name='Robecourtes',
        ),
        migrations.RenameModel(
            old_name='Basket_femme',
            new_name='Robelongues',
        ),
        migrations.RenameModel(
            old_name='Bijoux',
            new_name='Robesimples',
        ),
        migrations.RenameModel(
            old_name='T_shirt_femme',
            new_name='Robesoirees',
        ),
        migrations.RenameModel(
            old_name='Accessoire_de_meuble',
            new_name='Sandalsfemmes',
        ),
        migrations.RenameModel(
            old_name='Jupe_courte',
            new_name='Sandalshommes',
        ),
        migrations.RenameModel(
            old_name='Robe_simple',
            new_name='Tshirtfemmes',
        ),
        migrations.RenameModel(
            old_name='Perique_perruvienne',
            new_name='Tshirthommes',
        ),
        migrations.RenameModel(
            old_name='Jupe_longue',
            new_name='Tshirts',
        ),
        migrations.AlterModelOptions(
            name='accesoiredemodes',
            options={'ordering': ['-Date'], 'verbose_name': 'Accesoiredemode', 'verbose_name_plural': 'Accesoiresdemode'},
        ),
        migrations.AlterModelOptions(
            name='accessoiredemeubles',
            options={'ordering': ['-Date'], 'verbose_name': 'Accessoire_de_meuble', 'verbose_name_plural': 'Accessoires_de_meuble'},
        ),
        migrations.AlterModelOptions(
            name='basketfemmes',
            options={'ordering': ['-Date'], 'verbose_name': 'Basketfemme', 'verbose_name_plural': 'Basketfemmes'},
        ),
        migrations.AlterModelOptions(
            name='baskethommes',
            options={'ordering': ['-Date'], 'verbose_name': 'Baskethomme', 'verbose_name_plural': 'Baskethommes'},
        ),
        migrations.AlterModelOptions(
            name='baskets',
            options={'ordering': ['-Date'], 'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='bijouxfemmes',
            options={'ordering': ['-Date'], 'verbose_name': 'Bijouxfemme', 'verbose_name_plural': 'Bijouxfemmes'},
        ),
        migrations.AlterModelOptions(
            name='bijouxhommes',
            options={'ordering': ['-Date'], 'verbose_name': 'Bijouxhomme', 'verbose_name_plural': 'Bijouxhommes'},
        ),
        migrations.AlterModelOptions(
            name='bijouxs',
            options={'ordering': ['-Date'], 'verbose_name': 'Bijoux', 'verbose_name_plural': 'Bijoux'},
        ),
        migrations.AlterModelOptions(
            name='jupecourtes',
            options={'ordering': ['-Date'], 'verbose_name': 'Jupecourte', 'verbose_name_plural': 'Jupecourtes'},
        ),
        migrations.AlterModelOptions(
            name='jupelongues',
            options={'ordering': ['-Date'], 'verbose_name': 'Jupelongue', 'verbose_name_plural': 'Jupelongues'},
        ),
        migrations.AlterModelOptions(
            name='leshautsfemmes',
            options={'ordering': ['-Date'], 'verbose_name': 'Les-hautsfemme', 'verbose_name_plural': 'Les-hautsfemmes'},
        ),
        migrations.AlterModelOptions(
            name='leshautshommes',
            options={'ordering': ['-Date'], 'verbose_name': 'Les_hautshomme', 'verbose_name_plural': 'Les_hautshommes'},
        ),
        migrations.AlterModelOptions(
            name='machineelectroniques',
            options={'ordering': ['-Date'], 'verbose_name': 'Machine_electronique', 'verbose_name_plural': 'Machines_electronique'},
        ),
        migrations.AlterModelOptions(
            name='periquebresiliennes',
            options={'ordering': ['-Date'], 'verbose_name': 'Perique_brezilienne', 'verbose_name_plural': 'Periques_brezilienne'},
        ),
        migrations.AlterModelOptions(
            name='periquehumainhairs',
            options={'ordering': ['-Date'], 'verbose_name': 'Perique_humain_hair', 'verbose_name_plural': 'Perique_humain_hair'},
        ),
        migrations.AlterModelOptions(
            name='periquenaturels',
            options={'ordering': ['-Date'], 'verbose_name': 'Perique_naturel', 'verbose_name_plural': 'Perique_naturel'},
        ),
        migrations.AlterModelOptions(
            name='periqueperruviennes',
            options={'ordering': ['-Date'], 'verbose_name': 'Perique_perruvienne', 'verbose_name_plural': 'Periques_perruvienne'},
        ),
        migrations.AlterModelOptions(
            name='periquesinthetiques',
            options={'ordering': ['-Date'], 'verbose_name': 'Perique_sinthetique', 'verbose_name_plural': 'Periques_sinthetique'},
        ),
        migrations.AlterModelOptions(
            name='robecourtes',
            options={'ordering': ['-Date'], 'verbose_name': 'Robecourte', 'verbose_name_plural': 'Robecourtes'},
        ),
        migrations.AlterModelOptions(
            name='robelongues',
            options={'ordering': ['-Date'], 'verbose_name': 'Robelongue', 'verbose_name_plural': 'Robelongues'},
        ),
        migrations.AlterModelOptions(
            name='robesimples',
            options={'ordering': ['-Date'], 'verbose_name': 'Robe_simple', 'verbose_name_plural': 'Robe_simple'},
        ),
        migrations.AlterModelOptions(
            name='robesoirees',
            options={'ordering': ['-Date'], 'verbose_name': 'Robe_soiree', 'verbose_name_plural': 'Robe_soiree'},
        ),
        migrations.AlterModelOptions(
            name='sandalsfemmes',
            options={'ordering': ['-Date'], 'verbose_name': 'Sandalsfemme', 'verbose_name_plural': 'Sandalsfemmes'},
        ),
        migrations.AlterModelOptions(
            name='sandalshommes',
            options={'ordering': ['-Date'], 'verbose_name': 'Sandalshomme', 'verbose_name_plural': 'Sandalshommes'},
        ),
        migrations.AlterModelOptions(
            name='tshirtfemmes',
            options={'ordering': ['-Date'], 'verbose_name': 'T-shirtfemme', 'verbose_name_plural': 'T-shirtfemmes'},
        ),
        migrations.AlterModelOptions(
            name='tshirthommes',
            options={'ordering': ['-Date'], 'verbose_name': 'T-shirt-homme', 'verbose_name_plural': 'T-shirthommes'},
        ),
        migrations.AlterModelOptions(
            name='tshirts',
            options={'ordering': ['-Date'], 'verbose_name': 'T-shirt', 'verbose_name_plural': 'T-shirts'},
        ),
    ]
