# Generated by Django 4.2.3 on 2023-07-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_rename_basket_homme_accesoiredemodes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sandals',
            new_name='Sandal',
        ),
        migrations.AlterModelOptions(
            name='sandal',
            options={'ordering': ['-Date'], 'verbose_name': 'Sandal', 'verbose_name_plural': 'Sandals'},
        ),
    ]
