# Generated by Django 4.2.3 on 2023-07-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_rename_sandals_sandal_alter_sandal_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baskets',
            new_name='Basket',
        ),
        migrations.RenameModel(
            old_name='Baskethommes',
            new_name='Basketfemme',
        ),
        migrations.RenameModel(
            old_name='Basketfemmes',
            new_name='Baskethomme',
        ),
        migrations.AlterModelOptions(
            name='basketfemme',
            options={'ordering': ['-Date'], 'verbose_name': 'Basketfemme', 'verbose_name_plural': 'Basketfemmes'},
        ),
        migrations.AlterModelOptions(
            name='baskethomme',
            options={'ordering': ['-Date'], 'verbose_name': 'Baskethomme', 'verbose_name_plural': 'Baskethommes'},
        ),
    ]
