# Generated by Django 4.2.3 on 2023-07-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_rename_baskethomme_basketes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='img',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habits',
            name='img1',
            field=models.ImageField(default=' ', upload_to='images'),
            preserve_default=False,
        ),
    ]
