# Generated by Django 4.2.3 on 2023-07-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_habits_img_habits_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress_shop_contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=150)),
                ('dress_shop_information', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dress_shop_contact',
                'verbose_name_plural': 'Dress_shop_contacts',
                'ordering': ['-Date'],
            },
        ),
    ]
