# Generated by Django 4.2.3 on 2023-07-30 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0013_message_provenant_de_la_page_de_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_provenant_de_la_page_de_contact',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='message_provenant_de_la_page_de_contact',
            old_name='suject',
            new_name='subject',
        ),
    ]
