# Generated by Django 4.2.3 on 2023-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0014_rename_nom_message_provenant_de_la_page_de_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(auto_created=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top_1',
                'verbose_name_plural': 'Top_1',
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='Top_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(auto_created=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top_2',
                'verbose_name_plural': 'Top_2',
                'ordering': ['-Date'],
            },
        ),
        migrations.CreateModel(
            name='Top_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(auto_created=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix', models.IntegerField(default=0)),
                ('categorie', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top_3',
                'verbose_name_plural': 'Top_3',
                'ordering': ['-Date'],
            },
        ),
    ]
