# Generated by Django 4.2.3 on 2023-07-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0015_top_1_top_2_top_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_1',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='top_2',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='top_3',
            old_name='nom',
            new_name='name',
        ),
    ]
