# Generated by Django 4.2.3 on 2023-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0016_rename_nom_top_1_name_rename_nom_top_2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('sous_titre', models.CharField(max_length=150)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top',
                'verbose_name_plural': 'Top',
                'ordering': ['-Date'],
            },
        ),
    ]
