# Generated by Django 4.2.3 on 2023-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0017_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='top',
            name='titre_du_top_de_top',
            field=models.CharField(default=' ', max_length=150),
            preserve_default=False,
        ),
    ]
