# Generated by Django 4.2.3 on 2023-07-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_top_titre_du_top_de_top'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('Date', models.CharField(max_length=150)),
                ('heure', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenement',
                'ordering': ['-Date'],
            },
        ),
    ]
