# Generated by Django 4.2.3 on 2023-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0020_evenement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('proffesion', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['-Date'],
            },
        ),
        migrations.AlterField(
            model_name='evenement',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
